# Generated by Django 2.2.2 on 2019-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
