# Generated by Django 2.2.2 on 2019-06-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190630_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='category_id',
            new_name='category',
        ),
    ]
