# Generated by Django 2.2.2 on 2019-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190701_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
