# Generated by Django 2.2.3 on 2019-07-18 00:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190701_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z \\']*$", 'Should contain only alphabets')]),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='title',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator("^[a-zA-Z \\']*$", 'Should contain only alphabets')]),
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[a-zA-Z \\']*$", 'Should contain only alphabets')])),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('enum', 'Enum')], max_length=10)),
                ('value', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[a-zA-Z \\']*$", 'Should contain only alphabets')])),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='api.Favourite')),
            ],
        ),
    ]
