# Generated by Django 2.2.3 on 2019-07-29 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190726_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('old', django.contrib.postgres.fields.jsonb.JSONField()),
                ('new', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
