# Generated by Django 2.2.3 on 2019-07-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190729_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='model',
            field=models.CharField(choices=[('category', 'Category'), ('favourite', 'Favourite')], default='favourite', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10),
        ),
    ]
