# Generated by Django 2.2.3 on 2019-07-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190730_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='new',
            new_name='after',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='old',
            new_name='before',
        ),
    ]
